[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://quantrade-backend.onrender.com"
  VITE_WS_URL = "wss://quantrade-backend.onrender.com"
  VITE_APP_NAME = "QuantTrade Platform"

[context.deploy-preview.environment]
  VITE_API_URL = "https://quantrade-backend.onrender.com"
  VITE_WS_URL = "wss://quantrade-backend.onrender.com"

[context.branch-deploy.environment]
  VITE_API_URL = "https://quantrade-backend.onrender.com"
  VITE_WS_URL = "wss://quantrade-backend.onrender.com"