[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://site--quant-platform--lt5sgl89h54n.code.run"
  VITE_WS_URL = "wss://site--quant-platform--lt5sgl89h54n.code.run"
  VITE_APP_NAME = "QuantTrade Platform"

[context.deploy-preview.environment]
  VITE_API_URL = "https://site--quant-platform--lt5sgl89h54n.code.run"
  VITE_WS_URL = "wss://site--quant-platform--lt5sgl89h54n.code.run"

[context.branch-deploy.environment]
  VITE_API_URL = "https://site--quant-platform--lt5sgl89h54n.code.run"
  VITE_WS_URL = "wss://site--quant-platform--lt5sgl89h54n.code.run"